services:
  web:
    image: shinsenter/php:8.0-fpm-apache-alpine
    environment:
      DEBUG: "1"
      PHP_DISPLAY_ERRORS: "1"
      PHP_POST_MAX_SIZE: "100M"
      PHP_UPLOAD_MAX_FILESIZE: "100M"
      PHP_SESSION_COOKIE_HTTPONLY: "1"
      APP_UID: "1000"
      APP_GID: "1000"
    ports:
      - 2680:81
      - 2643:444
    volumes:
      - ./dist:/var/www/html/